---
- name: "ssl_exporter | Download & unarchive exporter binary from tarball"
  ansible.builtin.unarchive:
    src: "{{ vars['ssl_exporter_url'] + '/v' + vars['ssl_exporter_version'] +
      '/ssl_exporter_' + vars['ssl_exporter_version'] + '_' +
      vars['ssl_exporter_arch'] + '.tar.gz' }}"
    dest: "{{ vars['ssl_exporter_dest'] }}"
    remote_src: "yes"
    include: "ssl_exporter"
    mode: "0775"
    owner: "root"
    group: "root"
