---
- name: "Daemon reload"
  ansible.builtin.systemd:
    daemon_reload: "yes"
- name: "Restart ssl_exporter"
  ansible.builtin.systemd:
    name: "{{ vars['ssl_exporter_service'] }}"
    state: "restarted"
  when:
    - "hostvars[inventory_hostname]['ssl_exporter'] is defined"
    - "hostvars[inventory_hostname]['ssl_exporter'] != ''"
    - "hostvars[inventory_hostname]['ssl_exporter'] |
       community.general.json_query(vars['ssl_exporter_restart']) is defined"
    - "hostvars[inventory_hostname]['ssl_exporter'] |
       community.general.json_query(vars['ssl_exporter_restart']) == 'true'"
  vars:
    ssl_exporter_restart: "[] | map(&restart || 'false', @) | [0]"
